services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always

  python-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    