name = "sinod-admin"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[env.staging]
name = "sinod-admin-staging"
vars = { ENVIRONMENT = "staging" }

[env.production]
name = "sinod-admin"
vars = { ENVIRONMENT = "production" }

[[r2_buckets]]
binding = "R2"
bucket_name = "sinod-admin-assets"

[build]
command = "npm run build"
cwd = "."
watch_dir = "."
